import time
import plugins
import requests
import hangups
import logging
import random

logger = logging.getLogger(__name__)

def _initialise(bot):
    plugins.register_user_command(["topic"])

def topic(bot, event, *args):
    try:
        topics = ['Last trip you took, where?',
'Do you think the ladies really love Cool James?',
'How tall do you think Vladimir Putin is? (Apparently 5’7” or so)',
'Favorite professional sport?',
'If you could only have one alcoholic drink for the rest of your life, what would it be?',
'Bert or Ernie?',
'Can you ever have too much gluten?',
'Best Vacation you ever had. Where, and what is the most vivid memory from it today?',
'What’s your take on the mullet?',
'Was Rudy offsides?',
'What is the worst experience you have ever had on a plane?',
'Do you have any plans for Boxing day (December 26th)?',
'Which president served two non-consecutive terms?',
'How many presidents can you name?',
'Are you registered to donate your organs? (if not, give shame)',
'Favorite coffee drink?',
'Do you believe in Gaia Theory (The earth itself is a giant organism, and could actually be considered alive)?',
'Have you ever read a book that was not as good as the movie?',
'Travel Pillows, are they a great invention or an idiot collar?',
'Tom Selleck or his moustache?',
'Do you have a favorite social media platform?',
'What do you think the average number of dick pics a guy takes before he is happy with the photo?',
'Hipsters, are they cool, or are they too cool?',
'Does a Spoonful of sugar really make the medicine go down?',
'The best photo you ever took, what was it of?',
'Who do you think cooked most of this, Ian or Roxanne?',
'Favorite US city. Why?',
'Where you good this year, or do you expect coal, you naughty, naughty person?',
'What are your thoughts on a high-fiber diet?',
'Do you think Rose was being selfish on the door, or that the added weight of Jack would have caused the door to flounder? Could they have tried?',
'Do you believe in ghosts?',
'Do you think the New Deal worked?',
'What is the best childhood board game that turned into a drinking game?',
'Do you realize how significant the battle of Hastings (1066) is in todays English-speaking world?',
'What is the last book you read? Did you like it?',
'What is your favorite kind of sausage?',
'Can you believe how amazing this party is?',
'Is chewing tobacco gross, or totally disgusting?',
'Have you ever imagined Rainn Wilson naked?',
'Was Shackleton really brave, or really dumb, or both?',
'How do you know the hosts?',
'Outside of the humanly visible light spectrum, there exist colors we cannot see. Try to describe them.',
'Favorite book?',
'Can you fake any accents? Let’s hear it',
'A place you have always wanted to go',
'Do you have a weird celebrity crush? (Say “That’s weird” no matter what)',
'Do you think Pocahontas actually knew how high a sycamore grew, or was she just making a point?',
'How classy do I look right now? (Do something classy, as a test)',
'Did Ian show you his new hammer? Isn\'t it pretty awesome?',
'Which president served the shorted term?',
'Do you think suspenders should come back into style?',
'(Wink) Where is the mistletoe?',
'Why is tea so popular, it’s only warmed mud water',
'What is your favorite way to exercise?',
'Should the Top hat make a comeback?',
'Do you have a preferred drinking game?',
'Best movie you have seen in the last year',
'What do you think my best color is?',
'In Chesapeake, VA, a regionally famous battle took place. Can you name it? (follow up if yes, how long did it last, and how many casualties?)',
'Dinner with a living famous person, who would you choose?',
'Most underrated movie?',
'Name a time where you really made a difference in someone else’s life.',
'Tea or Coffee? (If Tea, just lie and say Coffee)',
'Have you seen any good movies lately?',
'Tell me your best Dad joke.',
'William of Occam: Do you think when he first postulated his now famous razor, that it would in fact be used as an arguing point against religion? (He was a priest)',
'Red wine, or white wine? (At this point, you should offer to fill their glass)',
'Puberty: Did you enjoy the process?',
'Chesapeake, VA. Does ‘Great Dismal Swamp’ truly capture the essence of the place, or would you use different descriptors?',
'Apple or Android?',
'Scariest flight experience you’ve had',
'Have you ever gone to the ER for something dumb and preventable (i.e. your fault)?',
'What is the highest elevation you have ever stood at? How did you get there?',
'Can a monocle ever be sexy?',
'Mountains or beach?',
'Favorite Van Morrison song?',
'If you could speak a language other than English, what would it be?',
'Favorite movie of all time?',
'Do you like my shoes?',
'Yoga pants in public. Why or why not?',
'What do you call carbonated beverages, Pop, Soda, Coke, Moxie, or something else equally dumb?',
'What is your favorite beverage?',
'Have any favorite palindromes?',
'How would you define ‘Class?’',
'What is your understanding of Brexit?',
'What do you think shark pee smells like?',
'Does your car have a name, and what is it?',
'Name the best pizza you have ever had.',
'Who is prettier, Idris Elba or Rick Fox?',
'Are these dogs cute, or fucking terrors?',
'Which former president, after creating a political party and losing the election, discovered a river that now bears his name in the Amazon? (Formerly the River of Doubt)',
'What would you like your legacy to be?',
'Ian is dressed really well tonight. I wonder who cuts his hair?',
'Fountain pens are the best',
'How haven’t I met you before, you are so very interesting and very attractive!',
'What is your favorite TV series?',
'What do you think dogs dream of?',
'Have you ever found anything in a hotel room?',
'Do you think that if Joan of Arc had been a boy/man, we would remember him today?',
'Did you ever own a Von Dutch hat? Where is it now?',
'What are you most proud of in your life right now?',
'The weather outside, eh?',
'Do you know where the highest recorded wind speed in the US took place?',
'Favorite dog breed?',
'Have you ever seen the Bayeux Tapestry in person?',
'Do you have a favorite style of beer?',
'What is your favorite thing to do with Excel?',
'Olives: Italian or Spanish?',
'Favorite app on your phone?',
'Main cause of the Civil War? ',
'If you could go back in time to witness one single event, what would it be and why?',
'Do you have a favorite Pope?',
'If you were Indiana Jones, would you carry your whip with you to the grocery store?',
'Do you think dolphins ever look out at a beach full of people and just sigh through their blowholes?',
'What would you define as sweater weather?',
'Best family vacation you can remember',
'Do you drive without your seatbelt fastened? (If so, place smack upon forehead. Either forehead)',
'Have you ever asked someone how the baby is going and they responded that they are not expecting?',
'Why are pedicures so relaxing?',
'How long do you think it took for Marie Antionette to fully grasp what was going to happen?',
'Do you have a faovrite anti-pope?',
'What is the longest you\'ve ever waited to be seated at a resuratant? Was it worth it?',
'Best meal of your life, who made it?',
'Can you remember the last letter you wrote?',
'Do you think public school uniforms are a good idea?',
'Favorite way to eat oysters?',
'What is the fastest you have ever driven?',
'Why would a woodchuck chuck wood?',
'The Detroit Lions: Will they ever even play in a Super Bowl?',
'Blues or Jazz? (Hint: Both)',
'Do you find it fun or sad that you are reading these?',
'Reading this, you must now walk away from the person you were talking to without saying anything.',
'Romp-hims.',
'Have you ever thrown up on a plane?',
'Have you ever texted something inappropriate to the wrong person? (Slipery slope here, watch out)',
'First thing you would do if you found out you won $27,000,000 ',
'What was your thought process with what you wore tonight?',
'How long did Ian work on these? Did he think we were all not great conversationalists?',
'Do you have a favorite explorer?',
'Would you rather be on an expedition to the Artic or the Amazon?',
'Do you know you are being recorded right now?',
'I have that same _____________ (Insert article of clothing)!',
'French Montana. Is he from either France or Montana? What\'s his deal?',
'What do you do during typical work hours?']
        topicMan = topics[random.randint(0, len(topics))]

    except:
        topicMan = "Unable to get topics right now"
        logger.exception(topic)

    yield from bot.coro_send_message(event.conv_id, topicMan)
